struct plot10 tktrnx_;

/*  define ploting code externals */

extern int adeout_ (int, int *);
extern int a1in_ (int *,int *); 
extern int a1out_ (int *, int *); 
extern int ainst_ (int *,int *); 
extern int alfmod_ ();
extern int ancho_ (int *); 
extern int anmode_ (); 
extern int anstr_ (int *,int *); 
extern int aoutst_ (int *,int *); 
extern int baksp_ (); 
extern int bell_ (); 
extern int buffpk_ (int *,int *); 
extern int cartn_ (); 
extern int chrsiz_ (int *); 
extern int clipt_ (float *, float *); 
extern int csize_ (int *,int *); 
extern int cwsend_ (); 
extern int czaxis_ (int *); 
extern int dasha_ (float *,float *,int *); 
extern int dashr_ (float *,float *,int *); 
extern int dashsa_ (float *,float *, int *); 
extern int dashsr_ (float *,float *,int *); 
extern int dcursr_ (int *, int *, int *); 
extern int drawa (float ,float ); 
extern int drawa_ (float * ,float  *); 
extern int drawr_ (float *,float *); 
extern int drawsa_ (float *, float *); 
extern int drawsa (float , float ); 
extern int drawsr_ (float *, float *); 
extern int drwabs_ (int * ,int * ); 
extern int drwabs (int ,int ); 
extern int drwrel_ (int *, int *); 
extern int drwrel (int , int ); 
extern int dshabs_ (int *, int * , int *); 
extern int dshmod_ (int *); 
extern int dshrel_ (int *, int *, int *); 
extern int dshrel (int , int , int ); 
extern int dwindo_ (float *,float *,float *,float *); 
extern int dwindo (float ,float ,float ,float ); 
extern int erase_ (); 
extern int erase (); 
extern int finitt_ (int *,int *); 
extern int finitt (int,int); 
extern int genflg_ (int *); 
extern int hdcopy_ (); 
extern int home_ (); 
extern int incplt_ (int *, int *, int *); 
extern int initt_ (int); 
extern int initt(int);
extern int iowait_ (int *); 
extern int ipmod_ (); 
extern int ka12as_ (int *, char *, char *); 
extern int kam2as_ (int *, char *, int *); 
extern int kas2a1_ (int *, int *, int *); 
extern int kas2am_ (int *, int *, char *); 
extern int kcm_ (float *); 
extern int kin_ (float *); 
extern int kin (float ); 
extern int leftio_ (int *); 
extern int linef_ (); 
extern int linhgt_ (int *); 
extern int lintrn_ (int *); 
extern int lintrn (int); 
extern int linwdt_ (int *); 
extern int logtrn_ (int *); 
extern int logtrn (int ); 
extern int lvlcht_ (); 
extern int movabs_ (int * ,int * ); 
extern int movabs (int ,int ); 
extern int movea (float ,float ); 
extern int movea_ (float * ,float  *); 
extern int mover_ (float *, float *); 
extern int movrel_ (int * , int *); 
extern int movrel (int  , int ); 
extern int newlin_ (); 
extern int newpag_ (); 
extern int parclt_ (float *,float *,float *,float *,float *,float *); 
extern int pclipt_ (float *, float *); 
extern int pltchr_ (int *,int *, int *); 
extern int pntabs_ (int *,int *); 
extern int pntmod_ (); 
extern int pntrel_ (int *,int *); 
extern int pointa_ (float *,float *); 
extern int pointa (float ,float ); 
extern int pointr_ (float *, float *); 
extern int poltrn_ (float *, float *, float *); 
extern int poltrn (float , float , float ); 
extern int pscal_ (); 
extern int recovr_ (); 
extern int rel2ab_ (float *, float *, float *, float *); 
extern int rescal_ (); 
extern int reset_ (); 
extern int restat_ (float *); 
extern int revcot_ (int *, int *, float *, float *); 
extern int rrotat_ (float *); 
extern int rscale_ (float *); 
extern int rsttab_ (int *, int *); 
extern int scursr_ (int *, int *, int *); 
extern int seebuf_ (int *); 
extern int seedw_ (float *,float *,float *,float *); 
extern int seeloc_ (int *, int *); 
extern int seemod_ (int *, int *, int *); 
extern int seemrg_ (int *, int *); 
extern int seerel_ (float *,float *,float *); 
extern int seetrm_ (int *,int *,int *,int *); 
extern int seetrn_ (float *, float *, int *); 
extern int seetw_ (int *,int *,int *,int *); 
extern int setbuf_ (int *); 
extern int setmrg_ (int *, int *); 
extern int settab_ (int *, int *); 
extern int svstat_ (float *); 
extern int swindo_ (int *,int *, int *,int *   ); 
extern int tabhor_ (int *); 
extern int tabver_ (int *); 
extern int term_ (int *, int *); 
extern int tinput_ (int *); 
extern int tinstr_ (int *, int *); 
extern int tkdash_ (int *, int *); 
extern int tkpnt_ (int *, int *); 
extern int toutpt_ (int *); 
extern int toutst_ (int *, int *); 
extern int tsend_ (); 
extern int ttblsz_ (int *); 
extern int twindo_ (int *,int *,int *,int *); 
extern int twindo (int ,int ,int ,int ); 
extern int v2st_ (int *, float *, float *, int *, int *); 
extern int vcursr_ (int *, float *, float *); 
extern int vecmod_ (); 
extern int vwindo_ (float *,float *,float *,float *); 
extern int vwindo (float ,float ,float ,float ); 
extern int wincot_ (float *, float *, int *, int *); 
extern int xycnvt_ (int *, int *); 

